<?php $ids = array("КАТАЛОГ" => "catalog", "НАШИ МАГАЗИНЫ" => "shops");
?>
<ul class="navigation">
    <?php foreach ($this->container as $page): ?>
 
    <li class="opened" <?php if(array_key_exists($page->getLabel(), $ids)):?> id="<?php echo $ids[$page->getLabel()] ?>" <?php endif;?>>
           
            <?php if (!empty($page->pages)): ?>
                <ul class="dopMenu">
                    <?php foreach ($page->pages as $subpage): ?>
                        <li>
                           <a href="#" class="withSymbol active"><span class="symbol">A</span>Телевизионная и кинореклама <i class="arrow"></i></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
    </li>
 
    <?php endforeach; ?>

</ul>