<div id="navbox">
    <?php foreach ($this->container as $page): ?>
        <?php if (!empty($page->pages)): ?>
            <?php foreach ($page->pages as $subpage): ?>
                <ul class="nav_cat">
                    <li>
                        <a <?php echo ($subpage->isActive(true)) ? 'class="active_menu"' : ''?>  href="<?php echo $subpage->getHref() ?>">
                            <?php echo $subpage->getLabel(); ?>
                        </a> </li>
                    <?php if (!empty($subpage->pages)): ?>
                        <ul class="nav_sub">
                            <?php foreach ($subpage->pages as $subsubpage): ?>
                                <li>
                                    <a <?php echo ($subsubpage->isActive(true)) ? 'class="active_menu"' : ''?> href="<?php echo $subsubpage->getHref(); ?>"><?php echo $subsubpage->getLabel(); ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>


                </ul>

            <?php endforeach; ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <ul class="nav_cat">
        <li>
            <a href="/categories?action=1">
                Акция
            </a> </li>
    </ul>

</div>
<!--vk-->
<script type="text/javascript">
VK.Widgets.Group("vk_groups", {mode: 0, width: "200", height: "400", color1: 'ebebeb', color2: '174867', color3: '3C4042'}, 35509659);
</script>
<!--vk-->
<!-- VK Widget -->
<div id="vk_groups"></div>