<div id="nav">
    <ul>
        <?php foreach ($this->container as $page): ?>
            <li>
                <a class="head_menu" href="<?php echo ($page->getHref()) ? $page->getHref() : 'javascript:void(0)'; ?>">
                    <?php echo $page->getLabel(); ?>
                </a>
                <?php if (!empty($page->pages)): ?>
                    <ul>
                        <?php foreach ($page->pages as $subpage): ?>
                            <li>
                                <a href="<?php echo ($subpage->getHref()) ? $this->escapehtml($subpage->getHref()) : 'javascript:void(0)'; ?>" ><?php echo $subpage->getLabel(); ?></a>
                                <?php if (!empty($subpage->pages)): ?>
                                    <ul >
                                        <?php foreach ($subpage->pages as $subsubpage): ?>
                                            <li>
                                                <a href="<?php echo $this->escapehtml($subsubpage->getHref()); ?>" ><?php echo $subsubpage->getLabel(); ?></a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        
    </ul>



</div>