<ul class="menu">

    <?php foreach ($this->container as $page): ?>
        <li <?php echo ($page->isActive() ? 'class="active"' : ''); ?>>
            <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>

            <?php if (!empty($page->pages)): ?>

                <ul class="dopMenu">
                    <?php foreach ($page->pages as $subpage): ?>
                        <li>
                            <a href="javascript:void(0)" class="main_link"><?php echo $subpage->getLabel(); ?></a>
                            
                           <?php if (!empty($subpage->pages)): ?>

                            <ul class="dopMenuUl" style="display:none;">
                                                <?php foreach ($subpage->pages as $subsubpage): ?>
                                                    <li>
                                                        <a href="<?php echo $subsubpage->getHref(); ?>"><?php echo $subsubpage->getLabel(); ?></a>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>

                                        <?php endif; ?>
                            
                            
                        </li>
                    <?php endforeach; ?>
                </ul>

            <?php endif; ?>
        </li>
    <?php endforeach; ?>

</ul>