<?php
$title = 'Удалить категорию';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Вы уверенны что хотите удалить категорию -
    '<?php echo $this->escapeHtml($category->name); ?>' ?>'?
</p>
<?php
$url = $this->url('category', array(
    'action' => 'delete',
    'id' => $this->id,
        ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $category->id; ?>" />
        <input type="submit" name="del" value="Да" />
        <input type="submit" name="del" value="Нет" />
    </div>
</form>