<?php
$title = 'Редактировать категорию';
$this->headTitle($title);
?>
<div class="panel-info">

    <div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
    <div class="panel-body well">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('category', array(
                    'action' => 'edit',
                    'id' => $this->id,
                        )
        ));
        $form->prepare();
        ?>
        <section>
            <div class="leftblock">

                <?php
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id'));
                ?>

                <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
                <dd>
                    <?php echo $this->formElement($form->get('name')); ?>
                    <?php echo $this->formElementErrors($form->get('name')); ?>
                </dd>

                <dt><?php echo $this->formLabel($form->get('description')); ?></dt>
                <dd>
                    <?php echo $this->formElement($form->get('description')); ?>
                    <?php echo $this->formElementErrors($form->get('description')); ?>
                </dd>

                <dt><?php echo $this->formRow($form->get('status')); ?></dt>


            </div>   

            <div class="rightblock">
                <a OnClick="ShowAddSubcat()" > Добавить подкатегорию</a>
                <div id="subcategory">
                    <?php
                    foreach ($subcategories as $subcategory) {
                        ?>
                        <div class="list">
                            <div class="error"></div>
                            <input type=text  value="<?php echo $subcategory['name'] ?>">   
                            <img  onClick="DelSubcat(this, '<?php echo $this->url('category', array('action' => 'deletesubcat')); ?>', '<?php echo $subcategory['id'] ?>')" src ="<?php echo '/img/backet.png' ?>">  
                            <img  onClick="EditSubcat(this, '<?php echo $this->url('category', array('action' => 'addsubcat')); ?>', '<?php echo $subcategory['id'] ?>', '<?php echo $subcategory['id_category'] ?>')" src ="<?php echo '/img/ico/edit.png' ?>">  
                        </div>
                        <?php
                    }
                    ?>
                </div>     
            </div>
            <div class="clear"></div>

    </div>
    <dd> <?php echo $this->formSubmit($form->get('submit')); ?></dd>
    <?php echo $this->form()->closeTag(); ?>
</section>
</div>

<div id="overlay-bg"></div>

<div id="subcat" class="popup roundbox">
    <a class="btn-close" href="javascript:void(0)" style="margin-top: 8px;"></a>
    <div class="title">Добавить подкатегрию</div>
    
    <div class="row">
        <div class="error"></div>
        <div class="col-xs-6">
            <input  id="sub_val" class="form-control" type="text" placeholder="Название подкатегории" value="">
        </div>
    </div>
    
    <div class="row-1 text-center paddind10">
        <input  OnClick="AddSubcat('<?php echo $this->id ?>', '<?php echo $this->url('category', array('action' => 'addsubcat')); ?>')" class ="btn btn-default" type="button" value=" Добавить подкатегорию"   />
    </div>
</div>
