<?php
$title = 'Категории';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('category', array('action' => 'add')); ?>">Add new category</a>
</p>
<table class="table">
    <tr>
        <th>Наименование</th>
        <th>Описание</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $category) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($category->name); ?></td>
            <td><?php echo $this->escapeHtml($category->description); ?></td>
            <td>
                <a href="<?php echo $this->url('category', array('action' => 'edit', 'id' => $category->id));
        ?>">Редактировать</a>
                <a href="<?php echo $this->url('category', array('action' => 'delete', 'id' => $category->id));
        ?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
echo $this->paginationControl(
// the paginator object
        $this->paginator,
// the scrolling style
        'sliding',
// the partial to use to render the control
        array('partial/paginator.phtml', 'Category'),
// the route to link to when a user clicks a control link
        array(    'route' => 'category'
        )
);
