<?php
$title = 'Категории';
$this->headTitle($title);
?>
<div class="panel-info">

    <div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
    <div class="panel-body well">
        <form class="panel form-inline" method="POST" action="<?php echo $this->url('category'); ?>">
            <div class=" panel-body" >
                <div class="form-group">
                    <label for="exampleInputName2">Наименование</label>
                    <input type="text" class="form-control" value="<?php echo $search['name'] ?>" name="data[name]" placeholder="Наименование">

                    <label for="exampleInputName2">Статус</label>
                    <select class="form-control" name="data[status]">
                        <option value="">Все</option>
                        <option <?php echo ($search['status'] == '1' ? 'selected' : '' ) ?> value="1">Показывать на сайте</option>
                        <option <?php echo ($search['status'] == '0' ? 'selected' : '' ) ?> value="0">Не отображать на сайте</option>
                    </select>

                </div>
                <button type="submit" class="btn btn-default">Поиск</button>
            </div>
        </form>

        <p>
            <a  class="btn btn-info"  href="<?php echo $this->url('category', array('action' => 'add')); ?>">Добавить новую категорию</a>
        </p>
        <table class="table">
            <tr>
                <th>Наименование</th>
                <th>Описание</th>
                <th>&nbsp;</th>
            </tr>
            <?php foreach ($this->paginator as $category) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($category->name); ?></td>
                    <td><?php echo $this->escapeHtml($category->description); ?></td>
                    <td>
                        <a class="btn btn-info" href="<?php echo $this->url('category', array('action' => 'edit', 'id' => $category->id)); ?>">
                            <img alt="Редактировать" src ="<?php echo '/img/ico/edit.png' ?>"/>   
                        </a>
                        <a class="btn btn-info" href="<?php echo $this->url('category', array('action' => 'delete', 'id' => $category->id)); ?>">
                            <img alt="Удалить" src ="<?php echo '/img/ico/del.png' ?>"/>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
<?php
echo $this->paginationControl(
// the paginator object
        $this->paginator,
// the scrolling style
        'sliding',
// the partial to use to render the control
        array('partial/paginator.phtml', 'Category'),
// the route to link to when a user clicks a control link
        array('route' => 'category'
        )
);
