<?php
$title = 'Добавить новый отзыв';
$this->headTitle($title);
?>
<div class="panel-info">

    <div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
    <div class="panel-body well">
<?php
$form->setAttribute('action', $this->url('reviews', array('action' => 'add')));
$form->prepare();?>

<section>
 <div class="infoshop">
        <?php
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        ?>

        <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </dd>
        
              
        <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </dd>
        
          <dt><?php echo $this->formLabel($form->get('phone')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('phone')); ?>
            <?php echo $this->formElementErrors($form->get('phone')); ?>
        </dd>

        <dt><?php echo $this->formLabel($form->get('description')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('description')); ?>
            <?php echo $this->formElementErrors($form->get('description')); ?>
        </dd>

        <dt><?php echo $this->formRow($form->get('status')); ?></dt>

 </div>
    </div>
    <dd>
 <?php echo $this->formSubmit($form->get('submit')); ?>
           <a href="/admin/reviews" class="btn btn-default">Назад</a> 
    </dd>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>
        
