<?php echo $this->doctype(); ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="keywords" content="доставка цветов, цветы с доставкой, доставка цветов минск, цветы с доставкой в минске, заказать цветы, цветы, цветы минск, цветы доставка минск,купить цветы,интернет, магазин, цветы, Минск,Лида,букет,роза,орхидея,лимон,fig,гламелия,сувениры,подарки,fig.by, цвет, доставка" />
        <meta name="description" content="Цветочные магазины в Минске и Лиде!" />
        
        
         <!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=28544101&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/28544101/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
style="width:88px; height:31px; border:0;display: none;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:28544101,lang:'ru'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter28544101 = new Ya.Metrika({id:28544101,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/28544101" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

        <?php echo $this->headTitle('GLAMELIA ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/'))
                ->prependStylesheet($this->basePath() . '/css/animate.css')
                ->prependStylesheet($this->basePath() . '/css/styles.css')
                ->prependStylesheet($this->basePath() . '/css/menu_cat.css')
                ->prependStylesheet($this->basePath() . '/css/ie.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery.slideshow.js')
                ->prependFile($this->basePath() . '/js/jquery.tmpl.min.js')
                ->prependFile($this->basePath() . '/js/scripts.js')
                ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')
        ;
        ?>

    </head>
    <body >
        <div id="body">
            <div id="header">
                <div class="center">               
                    <?php
                    $partial = array('partial/menu.phtml', 'default');
                    echo $this->navigation('public_navigation')->menu()
                            ->setMinDepth(1)
                            ->setMaxDepth(4)
                            ->setRenderParents(false)
                            ->setOnlyActiveBranch(true)
                            ->setPartial($partial)
                            ->render();
                    ?>
                </div>
            </div>
            <?php echo $this->content; ?>
        </div>

        <footer>
            <div id="footer">
                <p class="copyright">
                    <span>
                        <a href="http://vk.com/club35509659" target="_blank">
                            <img src="/img/vk.png">
                        </a>
                    </span>
                    © 2015 «Glamelia»
                </p>
            </div>
            <div class="mask"></div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
