<?php echo $this->doctype(); ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GLAMELIA ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))

                //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                // ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                //->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/animate.css')
                ->prependStylesheet($this->basePath() . '/css/styles.css')
                ->prependStylesheet($this->basePath() . '/css/menu_cat.css')
                ->prependStylesheet($this->basePath() . '/css/ie.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                //   ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                //   ->prependFile($this->basePath() . '/js/jquery.min.js')
                                ->prependFile($this->basePath() . '/js/jquery.slideshow.js')
                ->prependFile($this->basePath() . '/js/jquery.tmpl.min.js')
                //->prependFile($this->basePath() . '/js/modernizr.custom.04022.js')
                ->prependFile($this->basePath() . '/js/scripts.js')
                //->prependFile($this->basePath() . '/js/jquery.jcountdown-1.4.3.js')
             //   ->prependFile($this->basePath() . '/js/jquery.carouFredSel-6.2.1-packed.js')
                ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')
        ;
        ?>

    </head>
    <body >
        <div id="body">
            <div id="header">
                <div class="center">               
                    <?php
                    $partial = array('partial/menu.phtml', 'default');
                    echo $this->navigation('public_navigation')->menu()
                            ->setMinDepth(1)
                            ->setMaxDepth(4)
                            ->setRenderParents(false)
                            ->setOnlyActiveBranch(true)
                            ->setPartial($partial)
                            ->render();
                    ?>
                </div>
            </div>
            <?php echo $this->content; ?>
        </div>

        <footer>
            <div id="footer">
                <p class="copyright">
                    <span>
                        <a href="http://vk.com/club35509659" target="_blank">
                        <img src="/img/vk.png">
                        </a>
                    </span>
                    © 2015 «Glamelia»
                </p>
            </div>
            <div class="mask"></div>
        </footer>




        <?php echo $this->inlineScript() ?>
    </body>
</html>
