<?php
$title = 'Добавить новость';
$this->headTitle($title);
?>
<div class="panel-info">

    <div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
    <div class="panel-body well">
        <?php
        $form->setAttribute('action', $this->url('listnews', array('action' => 'add')));
        $form->prepare();
        ?>

        <section>
            <dl class="zend_form">
                <?php
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id'));
                ?>

                <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
                <dd>
                    <?php echo $this->formElement($form->get('name')); ?>
<?php echo $this->formElementErrors($form->get('name')); ?>
                </dd>

                <dt><?php echo $this->formLabel($form->get('description')); ?></dt>
                <dd>
                    <?php echo $this->formElement($form->get('description')); ?>
<?php echo $this->formElementErrors($form->get('description')); ?>
                </dd>

                <dt><?php echo $this->formRow($form->get('status')); ?></dt>


            </dl>


    </div>
</div>
<dd>
 <?php echo $this->formSubmit($form->get('submit')); ?>
    <a href="/admin/news" class="btn btn-default">Назад</a> 
</dd>
<?php echo $this->form()->closeTag(); ?>
</section>
