<?php
$title = 'Новости';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('listnews', array('action' => 'add')); ?>">
        Добавить новость</a>
</p>
<p>
    <a href="<?php echo $this->url('listnews', array('action' => 'index','status'=>1)); ?>">
       Показать неопубликованные</a>
</p>
<table class="table">
    <tr>
        <th>Название</th>
        <th>Описание</th>
        <th>Статус</th> 
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $news) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($news->name); ?></td>
            <td><?php echo $this->escapeHtml($news->description); ?></td>
            <td><?php echo $this->escapeHtml($news->status) ? 'опублекован' :'не обубликован' ?></td>
            <td>
                <a href="<?php echo $this->url('listnews', array('action' => 'edit', 'id' => $news->id));
        ?>">Редактировать</a>
                <a href="<?php echo $this->url('listnews', array('action' => 'delete', 'id' => $news->id));
        ?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
echo $this->paginationControl(
// the paginator object
        $this->paginator,
// the scrolling style
        'sliding',
// the partial to use to render the control
        array('partial/paginator.phtml', 'News'),
// the route to link to when a user clicks a control link
        array('route' => 'news'
        )
);
