<div id="content">
    <div class="center">               
        <div class="twoCol">
            <div class="shop_block" style="height: 1000px;">
                <div class="leftCol">
                    <?php
                    $partial = array('partial/category_menu.phtml', 'default');
                    echo $this->navigation('cat_navigation')
                            ->menu()
                            ->setMinDepth(1)
                            ->setMaxDepth(4)
                            ->setRenderParents(false)
                            ->setOnlyActiveBranch(true)
                            ->setPartial($partial)
                            ->render();
                    ?>
                </div>
                <div class="rightCol">
                    
                    
                    <div class="title">
                        <h1>Наши координаты</h1>
                    </div>
                    <div class="note taupe">
                        
                        <h2>О предприятии:</h2>
                        <p><?php echo $about->description ?></p>
                        
                        <p> <span>Наименование предприятия:</span>
                        <?php echo $about->name ?> </p>

                         <p><span>Адрес:</span>
                        <?php echo $about->address ?> </p>

                        <p> <span>Расчетный счет:</span>
                        <?php echo $about->current_account ?> </p>

                        <p><span>Информация о банке:</span>
                        <?php echo $about->bank_info ?></p>

                        <p><span>УНП:</span>
                        <?php echo $about->unp ?></p>

                        <p><span>ОКПО:</span>
                        <?php echo $about->okpo ?></p>

                        <p><span>Телефон:</span>
                        <?php echo $about->tel ?></p>

                        <p><span>Email:</span>
                        <?php echo $about->email ?></p>

                        <p><span>Директор:</span>
                        <?php echo $about->director ?></p>

                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>