<div id="content">
    <div class="center">   
        <div class="twoCol">
            <div class="shop_block" >
                <div class="leftCol raised">
                    <?php
                    $partial = array('partial/category_menu.phtml', 'default');
                    echo $this->navigation('cat_navigation')
                            ->menu()
                            ->setMinDepth(1)
                            ->setMaxDepth(4)
                            ->setRenderParents(false)
                            ->setOnlyActiveBranch(true)
                            ->setPartial($partial)
                            ->render();
                    ?>
                </div>
                <div class="rightCol">
                    <div class=title>
                        <?php
                        $title = 'Товары';
                        $this->headTitle($title);
                        ?>
                        <h1><?php
                            echo $this->escapeHtml($title);
                            $i = 0
                            ?></h1>
                    </div>
                    <section>
                        <ul class="lb-album">
                            <?php
                            foreach ($items as $item) {
                                $i++;
                                ?>
                                <li>
                                    <a href="#image-<?php echo $i ?>">
                                        <?php if ($item['patch']) : ?>
                                            <img src ="<?php echo '/images/item/small_' . trim($item['patch']) ?>" alt="image0<?php echo $i ?>">
                                        <?php else: ?>
                                            <img src ="<?php echo '/img/small_item.png' ?>" alt="image0<?php echo $i ?>">
                                        <?php endif ?>
                                        <?php if ($item['percentage']): ?>
                                            <div class="action">СКИДКА -<?php echo $this->escapehtml($item['percentage']) ?></div>
                                        <?php endif ?>
                                        <span> <?php echo $this->escapehtml($item['name']) ?></span>

                                    </a>


                                    <div class="lb-overlay" id="image-<?php echo $i ?>">

                                        <?php
                                        if ($item['patch']) {
                                            ?>
                                            <img src ="<?php echo '/images/item/big_' . trim($item['patch']) ?>" alt="image0<?php echo $i ?>">
                                        <?php } else { ?>
                                            <img src ="<?php echo '/img/small_item.png' ?>" alt="image0<?php echo $i ?>">
                                        <?php } ?>
                                        <div>
                                            <h3>
                                                <?php echo $this->escapeHtml($item['name']) ?>
                                            </h3>
                                            <p>
                                                <?php if ($item['action']): ?>
                                                    (Скидка - <?php echo $item['percentage'] ?>%)</br>
                                                <?php endif ?>
                                                <?php echo $this->escapehtml($item['description']) ?></p>

                                        </div>
                                        <a href="#page" class="lb-close">Закрыть</a>
                                    </div>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
