<div id="content">
    <div class="center">   
        <div class="twoCol">
            <div class="shop_block" style="height: 1000px;">
                <div class="leftCol">
                    <?php
                    $partial = array('partial/category_menu.phtml', 'default');
                    echo $this->navigation('cat_navigation')
                            ->menu()
                            ->setMinDepth(1)
                            ->setMaxDepth(4)
                            ->setRenderParents(false)
                            ->setOnlyActiveBranch(true)
                            ->setPartial($partial)
                            ->render();
                    ?>
                </div>
                <div class="rightCol">
                    <?php
                    $title = 'Товары';
                    $this->headTitle($title);
                    ?>
                    <h1><?php
                        echo $this->escapeHtml($title);
                        $i = 0
                        ?></h1>
                    <section>
                        <ul class="lb-album">
                            <?php
                            foreach ($items as $item) {
                                $i++;
                                ?>
                                <li>
                                    <a href="#image-<?php echo $i ?>">
                                        <?php if ($item['patch']) : ?>
                                            <img src ="<?php echo '/images/item/small_' . trim($item['patch']) ?>" alt="image0<?php echo $i ?>">
                                        <?php else: ?>
                                            <img src ="<?php echo '/img/small_item.png' ?>" alt="image0<?php echo $i ?>">
                                        <?php endif ?>

                                        <span> <?php echo $this->escapehtml($item['name'])?></span>
                                    </a>

                                    <div class="lb-overlay" id="image-<?php echo $i ?>">

                                        <?php
                                        if ($item['patch']) {
                                            ?>
                                            <img src ="<?php echo '/images/item/big_' . trim($item['patch']) ?>" alt="image0<?php echo $i ?>">
                                        <?php } else { ?>
                                            <img src ="<?php echo '/img/big_item.png' ?>" alt="image0<?php echo $i ?>">
                                        <?php } ?>
                                        <div>
                                            <h3><?php echo $item['name'] ?></h3>
                                            <p><?php echo $item['description'] ?></p>
                                        </div>
                                        <a href="#page" class="lb-close">x Close</a>
                                    </div>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
