<div id="content">
    <div class="center">
        <div class="shop_block" style="height: 1000px;">
        <div class="schedule">

             <div class="scheduleSlide">
    <!--news -->
            <div class="scheduleSlide">
                <?php
                foreach ($news as $new) {
                    ?>
                    <div class="scheduleSmall">
                        <p><?php echo $new['name'] ?></p>
                        <a href="#"><?php echo $new['description'] ?></a>
                    </div>
                    <?php
                }
                ?>
            </div>

                <!--отзывы -->
                <div class="scheduleSlide">
                    <?php
                    foreach ($reviews as $review) {
                        ?>
                        <div class="scheduleSmall">
                            <p><?php echo $review['name'] ?></p>
                            <a href="#"><?php echo $review['description'] ?></a>
                        </div>
                        <?php
                    }
                    ?>
                </div>
                <!--акции-->
                <div class="scheduleSlide">
                    <?php
                    foreach ($action_items as $item) {
                        ?>
                        <div class="scheduleSmall">
                            <p><span>-<?php echo $item['percentage'] ?></span></p>
                            <a href="<?php echo $this->url('items', array('action'=>'items','id' => $item['id'])); ?>"><?php echo $item['name'] ?></a>
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </div>
            <div class="right scheduleRight"></div>
            <div class="left scheduleLeft"></div>
        </div>

<div class="clear"></div>
        <div id="bigSlider">
            <div class="slideBack"></div>
            <div class="slideNext">
                <img class="previewPhoto" src="" alt="" />
                <div class="smallMask"></div>
                <span class="next"></span>
                <div class="nextText">
                    <span>Наши магазины</span>
                </div>
            </div>

            <div class="slider">
                <div class="slides">
                    <?php
                    foreach ($shops as $shop) {
                        ?>
                        <div class="slide">
                            <?php
                            $patchs = explode(',', $shop['patch']);
                            foreach ($patchs as $patch) {
                                ?>
                                <img src ="<?php echo '/images/shop/big_' . trim($patch) ?>">
                                <a href="<?php echo $this->url('shops', array('action'=>'shops','id' => $shop['id'])); ?>" class="slideText">
                                    <span>
                                        <span>
                                            <?php echo $shop['address'] ?>
                                        </span>
                                    </span>
                                </a>
                                <?php
                            }
                            ?>
                        </div>
                        <?php
                    }
                    ?>

                </div>
            </div>
        </div>
        <div class="indexContent clear">
            <!--     <div class="hits">
                  хиты продах
              </div>-->
            <?php
            foreach ($items as $item) {
                ?>
                <div class="flowers">
                    <?php
                    if ($item['patch']) {
                        ?>
                        <img src ="<?php echo '/images/item/small_' . trim($item['patch']) ?>">
                    <?php } else { ?>
                        <img src ="<?php echo '/img/small_item.png' ?>">
                    <?php } ?>
                    <a href="<?php echo $this->url('items', array('action'=>'items','id' => $item['id'])); ?>"><?php echo $item['name'] ?></a>
                </div>
                <?php
            }
            ?>
            <!--  <div class="apply">
                  <a href="#">
                      Наши <br/><span>Акции</span>
                  </a>
              </div>
            -->
        </div>
    </div>
    </div>
      </div>

