<div class="index">
    <div id="content" class="center ">
        <div class="schedule">
            <div class="scheduleSlider">
                <!-- новости
                <div class="scheduleSlide">
                    <div class="scheduleSmall">
                        <p>27.<span>09</span></p>
                        <a href="#">Повышение курса на 10%</a>
                    </div>
                    <div class="scheduleSmall">
                        <p>24.<span>09</span></p>
                        <a href="#">Повышение курса на 0%</a>
                    </div>
                    <div class="scheduleSmall">
                        <p>23.<span>09</span></p>
                        <a href="#">Смотрели новый фильм</a>
                    </div>
                    <div class="scheduleSmall">
                        <p>17.<span>08</span></p>
                        <a href="#">переделали сайт Red Apple</a>
                    </div>
                    <div class="scheduleSmall">
                        <p>27.<span>09</span></p>
                        <a href="#">Обладатели ololo</a>
                    </div>
                </div>

                <--отзывы -->
                <div class="scheduleSlide">
                    <?php
                    foreach ($reviews as $review) {
                        ?>
                        <div class="scheduleSmall">
                            <p><?php echo $review['name'] ?></p>
                            <a href="#"><?php echo $review['description'] ?></a>
                        </div>
                        <?php
                    }
                    ?>
                </div>
                <!--акции-->
                <div class="scheduleSlide">
                    <?php
                    foreach ($action_items as $item) {
                        ?>
                        <div class="scheduleSmall">
                            <p><span>-<?php echo $item['percentage'] ?></span></p>
                            <a href="#"><?php echo $item['name'] ?></a>
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </div>
            <div class="right scheduleRight"></div>
            <div class="left scheduleLeft"></div>
        </div>
        <div id="bigSlider">
            <div class="slideBack"></div>
            <div class="slideNext">
                <img class="previewPhoto" src="img/slider/small/02.jpg" alt="" />
                <div class="smallMask"></div>
                <span class="next"></span>
                <div class="nextText">
                    <span>Азия в Международном жюри фестиваля Red Apple</span>
                </div>
            </div>
            <div class="slider">
                <div class="slides">
                    <div class="slide">
                        <img src="img/slider/big/01.jpg" alt="" />
                        <a href="#" class="slideText">
                            <span>
                                <span>
                                    Россия и страны СНГ в Международном жюри фестиваля Red Apple
                                </span>
                            </span>
                        </a>
                    </div>
                    <div class="slide">
                        <img src="img/slider/big/02.jpg" alt="" />
                        <a href="#" class="slideText">
                            <span>
                                <span>
                                    Азия в Международном жюри фестиваля Red Apple
                                </span>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="indexContent clear">
          <!--     <div class="hits">
                хиты продах
            </div>-->
                <?php
                foreach ($items as $item) {
                    ?>
                    <div class="flowers">
                        <img src ="<?php echo '/images/item/small_' . $item['patch'] ?>">
                        <a href="#"><?php echo $item['name'] ?></a>
                    </div>
                    <?php
                }
                ?>
          <!--  <div class="apply">
                <a href="#">
                    Наши <br/><span>Акции</span>
                </a>
            </div>
          -->
        </div>
    </div>
</div>