<div id="content" class="center">
<div class="schedule">
                <div class="scheduleSlider">
                     <!-- новости-->
                    <div class="scheduleSlide">
                        <div class="scheduleSmall">
                            <p>27.<span>09</span></p>
                            <a href="#">Повышение курса на 10%</a>
                        </div>
                        <div class="scheduleSmall">
                            <p>24.<span>09</span></p>
                            <a href="#">Повышение курса на 0%</a>
                        </div>
                        <div class="scheduleSmall">
                            <p>23.<span>09</span></p>
                            <a href="#">Смотрели новый фильм</a>
                        </div>
                        <div class="scheduleSmall">
                            <p>17.<span>08</span></p>
                            <a href="#">переделали сайт Red Apple</a>
                        </div>
                        <div class="scheduleSmall">
                            <p>27.<span>09</span></p>
                            <a href="#">Обладатели ololo</a>
                        </div>
                    </div>
                    <!--отзывы -->
                    <div class="scheduleSlide">
                        <div class="scheduleSmall">
                            <p>Антон</p>
                            <a href="#">кртой буке</a>
                        </div>
                        <div class="scheduleSmall">
                            <p>Иван</p>
                            <a href="#">Работы-победители</a>
                        </div>
                        <div class="scheduleSmall">
                            <p>Ирина</p>
                            <a href="#">Но зачем?</a>
                        </div>
                        <div class="scheduleSmall">
                            <p>17.<span>08</span></p>
                            <a href="#">Обладатели «Приза СМИ» фестиваля Red Apple</a>
                        </div>
                        <div class="scheduleSmall">
                            <p>Мистер</p>
                            <a href="#">Обладатели «Приза СМИ» </a>
                        </div>
                    </div>
                    <!--акции-->
                    <div class="scheduleSlide">
                        <div class="scheduleSmall">
                            <p><span>-10%</span></p>
                            <a href="#">На сувниры которые продали</a>
                        </div>
                        <div class="scheduleSmall">
                            <p><span>-30%</span></p>
                            <a href="#">трататуськи тра та та </a>
                        </div>
                        <div class="scheduleSmall">
                            <p><span>-20%</span></p>
                            <a href="#">тру ла ла</a>
                        </div>
                        <div class="scheduleSmall">
                            <p><span>-90%</span></p>
                            <a href="#">на свадебные</a>
                        </div>
                        <div class="scheduleSmall">
                            <p><span>-0%</span></p>
                            <a href="#">срез розы</a>
                        </div>
                    </div>
                </div>
                <div class="right scheduleRight"></div>
                <div class="left scheduleLeft"></div>
            </div>
            <div id="bigSlider">
                <div class="slideBack"></div>
                <div class="slideNext">
                    <img class="previewPhoto" src="img/slider/small/02.jpg" alt="" />
                    <div class="smallMask"></div>
                    <span class="next"></span>
                    <div class="nextText">
                        <span>Азия в Международном жюри фестиваля Red Apple</span>
                    </div>
                </div>
                <div class="slider">
                    <div class="slides">
                        <div class="slide">
                            <img src="img/slider/big/01.jpg" alt="" />
                            <a href="#" class="slideText">
                                <span>
                                    <span>
                                        Россия и страны СНГ в Международном жюри фестиваля Red Apple
                                    </span>
                                </span>
                            </a>
                        </div>
                        <div class="slide">
                            <img src="img/slider/big/02.jpg" alt="" />
                            <a href="#" class="slideText">
                                <span>
                                    <span>
                                        Азия в Международном жюри фестиваля Red Apple
                                    </span>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="indexContent clear">
                <div class="hits">
                    хиты продах
                </div>
                <div class="flowers">
                    <img src="img/peoples/02.jpg" alt="" />
                    <a href="#">Пидор ебыный</a>
                </div>
                <div class="flowers">
                    <img src="img/peoples/03.jpg" alt="" />
                    <a href="#">Григорий Сорокин</a>
                </div>
                <div class="apply">
                    <a href="#">
                        Наши <br/><span>Акции</span>
                    </a>
                </div>
                <div class="flowers">
                    <img src="img/peoples/01.jpg" alt="" />
                    <a href="#">Григорий Сорокин</a>
                </div>
                <div class="flowers">
                    <img src="img/peoples/04.jpg" alt="" />
                    <a href="#">Григорий Сорокин</a>
                </div>
                <div class="flowers">
                    <img src="img/peoples/05.jpg" alt="" />
                    <a href="#">Григорий Сорокин</a>
                </div>
                <div class="flowers">
                    <img src="img/peoples/06.jpg" alt="" />
                    <a href="#">Григорий Сорокин</a>
                </div>
                <div class="flowers">
                    <img src="img/peoples/07.jpg" alt="" />
                    <a href="#">Григорий Сорокин</a>
                </div>
                <div class="flowers">
                    <img src="img/peoples/08.jpg" alt="" />
                    <a href="#">Григорий Сорокин</a>
                </div>
            </div>
</div>