<div id="content">
    <div class="center">               
        <div class="twoCol">
            <div class="shop_block" >
                <div class="leftCol raised">
                    <?php
                    $partial = array('partial/category_menu.phtml', 'default');
                    echo $this->navigation('cat_navigation')
                            ->menu()
                            ->setMinDepth(1)
                            ->setMaxDepth(4)
                            ->setRenderParents(false)
                            ->setOnlyActiveBranch(true)
                            ->setPartial($partial)
                            ->render();
                    ?>
                </div>
                <div class="rightCol">
                    <div class="title">
                        <h1><?php echo $this->escapeHtml($new->name); ?></h1>
                    </div>
                    <div class="note taupe">
                        <p><?php echo $new->description ?>
                            </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
