<div id="content">
    <div class="center">               
        <div class="twoCol">
            <div class="rightCol">
                <div class="shop_title">
                    <h1><?php echo $this->escapeHtml($new->name); ?></h1>
                </div>
                <p class="bigLine"></p>
                <?php echo $new->description ?>
            </div>
        </div>


    </div>
</div>
