<?php
$title = 'Отзывы';
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('review', array('action' => 'review')));
$form->prepare();
?>
<div id="content">
    <div class="center">               
        <div class="twoCol">
            <div class="shop_block">
                <div class="leftCol raised">
                    <?php
                    $partial = array('partial/category_menu.phtml', 'default');
                    echo $this->navigation('cat_navigation')
                            ->menu()
                            ->setMinDepth(1)
                            ->setMaxDepth(4)
                            ->setRenderParents(false)
                            ->setOnlyActiveBranch(true)
                            ->setPartial($partial)
                            ->render();
                    ?>
                </div>

                <div class="rightCol">

                    <div class="title">
                        <h1><?php echo $this->escapeHtml($title); ?></h1>
                                              
                    </div>
                    <blockquote class="oval-quotes">
				<p class="showReviewsForm">Нажмите сюда что бы оставить свои пожелания и благодарности!</p>
			</blockquote>

                    
                    <div class="review_form_add animated" style="position: absolute;">
                         <a class="btn-close" href="javascript:void(0)" style="margin-top: 8px;"></a>
                        <section>

                            <?php
                            echo $this->form()->openTag($form);
                            echo $this->formHidden($form->get('id'));
                            ?>
                            <div class="form-group">
                                <?php echo $this->formLabel($form->get('name')); ?>
                                <div class="error"></div>
                                <?php echo $this->formElement($form->get('name')); ?>
                                

                            </div>
                            <div class="form-group">
                                <?php echo $this->formLabel($form->get('phone')); ?>
                                <div class="error"></div>
                                <?php echo $this->formElement($form->get('phone')); ?>
                                

                            </div>
                            <div class="form-group">
                                <?php echo $this->formLabel($form->get('email')); ?>
                                <div class="error"></div>
                                <?php echo $this->formElement($form->get('email')); ?>
                                

                            </div>
                            <div class="form-group">
                                <?php echo $this->formLabel($form->get('description')); ?>
                                <div class="error"></div>
                                <?php echo $this->formElement($form->get('description')); ?>
                                
                            </div>
                            <input type="hidden" name="status" value="hidden">
                            <input type="button" class="btn btn-danger" onClick="ValidateRew()" value="Добавить">
                            <?php echo $this->form()->closeTag(); ?>


                        </section>  
                    </div>
                    
                    <?php foreach ($this->paginator as $reviews) : ?>
                        <blockquote class="example-obtuse">
                            <p> 
                                <?php echo $this->escapeHtml($reviews->description); ?>
                            </p>
                        </blockquote>
                        <p><?php echo $this->escapeHtml($reviews->name); ?></p>
                    <?php endforeach; ?>
                       
                </div>
            </div>
        </div>
    </div>
</div>
