        <?php
            $title ='Отзывы';
            $this->headTitle($title);?>
        <?php
            $form->setAttribute('action', $this->url('review', array('action' => 'review')));
            $form->prepare();?>
        <div id="content">
            <div class="center">               
                <div class="twoCol">
                    <div class="rightCol">
                        <h1 class="reviewsTitle"><?php echo $this->escapeHtml($title); ?></h1>
                        <p class="bigLine"></p><button class="btn btn-default showReviewsForm">+</button>
                        <div class="review_form_add animated">
                            <section>

                                    <?php
                                    echo $this->form()->openTag($form);
                                    echo $this->formHidden($form->get('id'));
                                    ?>
                                    <div class="form-group">
                                        <?php echo $this->formLabel($form->get('name')); ?>
                                        <?php echo $this->formElement($form->get('name')); ?>
                                        <?php echo $this->formElementErrors($form->get('name')); ?>

                                    </div>
                                    <div class="form-group">
                                        <?php echo $this->formLabel($form->get('phone')); ?>
                                        <?php echo $this->formElement($form->get('phone')); ?>
                                        <?php echo $this->formElementErrors($form->get('phone')); ?>

                                    </div>
                                    <div class="form-group">
                                        <?php echo $this->formLabel($form->get('email')); ?>
                                        <?php echo $this->formElement($form->get('email')); ?>
                                        <?php echo $this->formElementErrors($form->get('email')); ?>

                                    </div>
                                    <div class="form-group">
                                        <?php echo $this->formLabel($form->get('description')); ?>
                                        <?php echo $this->formElement($form->get('description')); ?>
                                        <?php echo $this->formElementErrors($form->get('description')); ?>
                                    </div>
                                        <?php echo $this->formSubmit($form->get('submit')); ?>
                                    <?php echo $this->form()->closeTag(); ?>


                            </section>  
                        </div>
                        <div class="publick_reviews"></div>
                    </div>
                </div>
            </div>
        </div>