<script type="text/javascript" src="/js/map.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<?php echo $key_map ?>&sensor=false&libraries=places""></script>
<?php
$title = 'Mагазин';
$this->headTitle($title);
print_r($shop)
?>


<div id="content">
    <div class="center">
        <div class="twoCol">
            <div class="shop_block" style="height: 1000px;">
            <div class="leftCol">
                <ul class="navigation">
                    <li>
                        <a href="#">Принять участие <i class="arrow"></i></a>
                    </li>
                    <li  class="active">
                        <a href="#">номинации <i class="arrow"></i></a>
                        <ul class="dropMenu">
                            <li>
                                <a href="#" class="withSymbol active"><span class="symbol">A</span>Телевизионная и кинореклама <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">B</span>Печатная реклама <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">C</span>Видеомастерство <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">D</span>Этикетка и упаковка <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">E</span>Телевизионная и кинореклама <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">F</span>Печатная реклама <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">A</span>Видеомастерство <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">B</span>Этикетка и упаковка <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">C</span>Медиапроекты <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">D</span>Red Apple Awards (интернет): международные номинации <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">E</span>Этикетка и упаковка <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">F</span>Медиапроекты <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">A</span>Red Apple Awards (интернет): международные номинации <i class="arrow"></i></a>
                            </li>

                        </ul>
                    </li>
                    <li>
                        <a href="#">правила подачи работ <i class="arrow"></i></a>
                    </li>
                    <li>
                        <a href="#">награды <i class="arrow"></i></a>
                    </li>
                    <li>
                        <a href="#">победители прошлых лет <i class="arrow"></i></a>
                    </li>
                    <li>
                        <a href="#">молодые креаторы <i class="arrow"></i></a>
                    </li>
                </ul>
            </div>
            <div class="rightCol">
                <div class="shop_title">
                    <h1><?php echo $this->escapeHtml($title); ?></h1>
                </div>
                <p class="bigLine"></p>

                <div id="bigSlider">
                    

                    <div class="slider">
                        <div class="slides">
                            <?php
                            foreach ($photos as $patch) {
                                ?>
                                <div class="slide">
                                    <img src ="<?php echo '/images/shop/big_' . trim($patch) ?>">
                                </div>
                                <?php
                            }
                            ?>

                        </div>
                    </div>
                </div>
                <label>Наш адрес: <?php echo $shop->address ?></label>
                <label>Время работы: <?php echo $shop->work_time ?></label>
                <h3> Схема проезда</h3>
                <div class="map_block">
                    <input type="hidden" id="end" value="<?php echo $shop->address ?>">
                    <div class="map-view-book">
                        <input id="location"   type="hidden" value="" />
                        <div id="map_canvas"></div>
                    </div>
                </div>

            </div>
            </div>
        </div>




    </div>


</div>



