<script type="text/javascript" src="/js/map.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<?php echo $key_map ?>&sensor=false&libraries=places""></script>
<?php
$title = 'Mагазин';
$this->headTitle($title);

$catalog = $this->navigation('public_navigation')->findOneByLabel('КАТАЛОГ');
$options = array(
   //'indent'  => 16,
    //'ulClass' => 'dopMenu',
);
$partial = array('partial/menu.phtml', 'default');
echo $this->navigation('public_navigation')
          ->menu()
          ->setPartial($partial)
          ->renderMenu($catalog,$options);

?>


<div id="content">
    <div class="center">
        <div class="twoCol">
            <div class="shop_block" style="height: 1000px;">
            <div class="leftCol">
                <ul class="navigation">
                    <?php foreach ($this->container as $page): ?>
                    <li>
                        <a href="<?php echo $page->getHref(); ?>" ><?php echo $page->getLabel(); ?><i class="arrow"></i></a>
                        <a href="#">Принять участие <i class="arrow"></i></a>
                    </li>
                    <li <?php echo ($page->isActive() ? 'class="active"' : ''); ?> class="active">
                        <a href="#"><i class="arrow"></i></a>
                        <ul class="dropMenu">
                            <li>
                                <a href="#" class="withSymbol active"><span class="symbol">A</span>Телевизионная и кинореклама <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">B</span>Печатная реклама <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">C</span>Видеомастерство <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">D</span>Этикетка и упаковка <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">E</span>Телевизионная и кинореклама <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">F</span>Печатная реклама <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">A</span>Видеомастерство <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">B</span>Этикетка и упаковка <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">C</span>Медиапроекты <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">D</span>Red Apple Awards (интернет): международные номинации <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">E</span>Этикетка и упаковка <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">F</span>Медиапроекты <i class="arrow"></i></a>
                            </li>
                            <li>
                                <a href="#" class="withSymbol"><span class="symbol">A</span>Red Apple Awards (интернет): международные номинации <i class="arrow"></i></a>
                            </li>

                        </ul>
                    </li>
                    <li>
                        <a href="#">правила подачи работ <i class="arrow"></i></a>
                    </li>
                    <li>
                        <a href="#">награды <i class="arrow"></i></a>
                    </li>
                    <li>
                        <a href="#">победители прошлых лет <i class="arrow"></i></a>
                    </li>
                    <li>
                        <a href="#">молодые креаторы <i class="arrow"></i></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="rightCol">
                <div class="shop_title">
                    <h1><?php echo $this->escapeHtml($title); ?></h1>
                </div>
                <p class="bigLine"></p>

                <div id="bigSlider">
                    

                    <div class="slider">
                        <div class="slides">
                            <?php
                            foreach ($photos as $patch) {
                                ?>
                                <div class="slide">
                                    <img src ="<?php echo '/images/shop/big_' . trim($patch) ?>">
                                </div>
                                <?php
                            }
                            ?>

                        </div>
                    </div>
                </div>
                <p><label>Наш адрес: </label> <?php echo $shop->address ?></p>
                <div><label>Режим работы: </label>
                    <?php for ($i=0; $i<7; $i++)
                    echo '<div class="work_day" title="' . $shop->work_time .'"></div>'
                    ?>
                </div>
                <h3> Схема проезда</h3>
                <div class="map_block">
                    <input type="hidden" id="end" value="<?php echo $shop->address ?>">
                    <div class="map-view-book">
                        <input id="location"   type="hidden" value="" />
                        <div id="map_canvas"></div>
                    </div>
                </div>

            </div>
            </div>
        </div>




    </div>


</div>



