<?php
$title = 'Добавить новый товар';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('item', array('action' => 'add')));
$form->prepare();
?>
<section>
    <dl class="zend_form">

        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('id')); ?>

        <dt><?php echo $this->formLabel($form->get('category_id')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('category_id')); ?>
            <?php echo $this->formElementErrors($form->get('category_id')); ?>
        </dd>
        
         <dt><?php echo $this->formLabel($form->get('subcategory_id')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('subcategory_id')); ?>
            <?php echo $this->formElementErrors($form->get('subcategory_id')); ?>
        </dd>
        
        <dt><?php echo $this->formLabel($form->get('shop_id')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('shop_id')); ?>
            <?php echo $this->formElementErrors($form->get('shop_id')); ?>
        </dd>


        <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </dd>


        <dt><?php echo $this->formRow($form->get('status')); ?></dt>

        <dt><?php echo $this->formLabel($form->get('id_photo')); ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('id_photo')); ?>
            <?php echo $this->formElementErrors($form->get('id_photo')); ?>
        </dd>
        <dd> <?php echo $this->formSubmit($form->get('submit')); ?>
        
        <a href="/admin/item" class="button">Назад</a>
        </dd>

        <?php echo $this->form()->closeTag(); ?>

    </dl>
</section>

