<?php
$title = 'Удалить товар';
$this->headTitle($title);
?>
 <div class="panel-info">

    <div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
    <div class="panel-body well">
<p>Вы уверены что хотите удалить
    '<?php echo $this->escapeHtml($item->name); ?>'?
</p>
<?php
$url = $this->url('item', array(
    'action' => 'delete',
    'id' => $this->id,
        ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $item->id; ?>" />
        <input type="submit" name="del" value="Да" />
        <input type="submit" name="del" value="Нет" />
    </div>
</form>