<?php
$title = 'Товары';
$this->headTitle($title);
?>
 <h3><?php echo $this->escapeHtml($title); ?></h3> 
<form class="panel form-inline" method="POST" action="<?php echo $this->url('item'); ?>">
    <div class=" panel-body" >
       <input type="hidden" name="fast" value="true">
        <div class="form-group">
            <label for="exampleInputName2">Наименование</label>
            <input type="text" class="form-control" name="query" placeholder="Наименование товара">
        </div>
        <button type="submit" class="btn btn-default">Поиск</button>
    </div>
</form>




<p>
    <a class="btn btn-info" href="<?php echo $this->url('item', array('action' => 'add')); ?>">Добавить новый товар</a>
</p>
<table class="table">
    <tr>
        <th>Наименование</th>
        <th></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $item) : ?>
        <tr>

            <td><?php echo $this->escapeHtml($item->name); ?></td>
            <td></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('item', array('action' => 'edit', 'id' => $item->id));
        ?>">
                    <img alt="Редактировать" src ="<?php echo '/img/ico/edit.png' ?>"/>    
                </a>
                <a class="btn btn-info" href="<?php echo $this->url('item', array('action' => 'delete', 'id' => $item->id)); ?>">
                    <img alt="Удалить" src ="<?php echo '/img/ico/del.png' ?>"/>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
echo $this->paginationControl(
// the paginator object
        $this->paginator,
// the scrolling style
        'sliding',
// the partial to use to render the control
        array('partial/paginator.phtml', 'Item'),
// the route to link to when a user clicks a control link
        array('route' => 'item'
        )
);
